#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#
# Usage:
#
#   getcov <PROJECT_NAME> open|supress_open
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

LCOV_INFO=$1
OPEN=$2

remove_old_report()
{
    pushd "${BUILT_PRODUCTS_DIR}"
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd "${BUILT_PRODUCTS_DIR}"
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    LCOV --remove ${LCOV_INFO} "Developer/SDKs/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "FBTweak/*" -d "{OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "Mixpanel/*" -d "{OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "Intuit Animation Engine/*" -d "{OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "SSZipArchive/*" -d "{OBJ_DIR}" -o ${LCOV_INFO}
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
}

generate_and_open_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report

[[ ${OPEN} == open ]] && generate_and_open_report || generate_report
