#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#
# Usage:
#
#   getcov <PROJECT_NAME> <REPORT_DIR>
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

PROJECT_NAME=$1
REPORT_DIR=$2

remove_old_report()
{
    pushd "${BUILT_PRODUCTS_DIR}"
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd "${BUILT_PRODUCTS_DIR}"
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${PROJECT_NAME}
}

exclude_data()
{
    LCOV --remove ${PROJECT_NAME} "Developer/SDKs/*" -d "${OBJ_DIR}" -o ${PROJECT_NAME}
    LCOV --remove ${PROJECT_NAME} "main.m" -d "${OBJ_DIR}" -o ${PROJECT_NAME}
    LCOV --remove ${PROJECT_NAME} "FBTweak/*" -d "{OBJ_DIR}" -o ${PROJECT_NAME}
    LCOV --remove ${PROJECT_NAME} "Mixpanel/*" -d "{OBJ_DIR}" -o ${PROJECT_NAME}
    LCOV --remove ${PROJECT_NAME} "Intuit Animation Engine/*" -d "{OBJ_DIR}" -o ${PROJECT_NAME}
    LCOV --remove ${PROJECT_NAME} "SSZipArchive/*" -d "{OBJ_DIR}" -o ${PROJECT_NAME}
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory ${REPORT_DIR} ${PROJECT_NAME}
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
